repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--safe]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: debug-statements

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        language_version: python3
        args: ["--max-line-length=160"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        files: .py$
        args: ["--config-file=mypy.ini"]

-   repo: local
    hooks:
    -   id: pytest
        name: my_pytest
        entry: py.test
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]
