version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.10"
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install pyinstaller
      - run: pyinstaller --onefile --windowed main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.10"
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: py.test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
